# Generated by Django 2.0.2 on 2018-02-04 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koch', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Menue',
                'verbose_name_plural': 'Menues',
            },
        ),
        migrations.CreateModel(
            name='Rezept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30)),
                ('kommentar', models.TextField()),
                ('fuer_kinder', models.IntegerField(help_text='Anzahl der Kinder')),
                ('fuer_erwachsene', models.IntegerField(help_text='Anzahl der Erwachsenen')),
                ('zubereitung', models.TextField()),
                ('anmerkungen', models.TextField()),
                ('ist_vorspeise', models.BooleanField(help_text='kann als Vorspeise dienen')),
                ('ist_hauptgang', models.BooleanField(help_text='kann als Hauptgang dienen')),
                ('ist_nachtisch', models.BooleanField(help_text='kann als Nachtisch dienen')),
                ('kategorie', models.CharField(choices=[('Reis', 'Reis'), ('Teigw.', 'Teigwaren'), ('Getr.', 'Getreide'), ('Kart.', 'Kartoffeln'), ('Gemüse', 'Gemüse'), ('Suppe', 'Suppe'), ('Fisch', 'Fischgericht'), ('Liebl.', 'Lieblingsgericht')], help_text='Art des Essens', max_length=6)),
                ('version', models.IntegerField(default=1)),
                ('_preis', models.IntegerField(default=0, help_text='kann leer sein, wird dann automatisch berechnet')),
                ('eingegeben_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RezeptZutat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menge', models.FloatField()),
                ('menge_qualitativ', models.CharField(max_length=15)),
                ('nummer', models.IntegerField()),
                ('rezept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zutaten', to='rezepte.Rezept')),
            ],
        ),
        migrations.CreateModel(
            name='Zutat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('einheit', models.CharField(default='', max_length=10)),
                ('preis_pro_einheit', models.IntegerField()),
                ('menge_pro_einheit', models.IntegerField()),
                ('masseinheit', models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('St.', 'St.'), ('Pckg.', 'Pckg.')], max_length=5)),
                ('kategorie', models.CharField(choices=[('Milch', 'Milchprodukt'), ('Gemüse', 'Gemüse'), ('Obst', 'Obst'), ('Getr.', 'Getreide'), ('Grund.', 'Grundnahrungsmittel'), ('Fisch', 'Fisch'), ('Gewürz', 'Gewürz'), ('Sonst.', 'Sonstiges')], max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='rezeptzutat',
            name='zutat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verwendung', to='rezepte.Zutat'),
        ),
        migrations.AddField(
            model_name='menue',
            name='hauptgang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hauptgang', to='rezepte.Rezept'),
        ),
        migrations.AddField(
            model_name='menue',
            name='nachtisch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nachtisch', to='rezepte.Rezept'),
        ),
        migrations.AddField(
            model_name='menue',
            name='vorspeise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vorspeise', to='rezepte.Rezept'),
        ),
    ]
