# Generated by Django 2.0.2 on 2018-02-04 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menue',
            options={'verbose_name': 'Menü', 'verbose_name_plural': 'Menüs'},
        ),
        migrations.AlterModelOptions(
            name='rezept',
            options={'verbose_name': 'Rezept', 'verbose_name_plural': 'Rezepte'},
        ),
        migrations.AlterModelOptions(
            name='rezeptzutat',
            options={'verbose_name': 'Rezeptzutat', 'verbose_name_plural': 'Rezeptzutaten'},
        ),
        migrations.AlterModelOptions(
            name='zutat',
            options={'verbose_name': 'Zutat', 'verbose_name_plural': 'Zutaten'},
        ),
        migrations.AddField(
            model_name='menue',
            name='datum',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rezept',
            name='zutaten',
            field=models.ManyToManyField(through='rezepte.RezeptZutat', to='rezepte.Zutat'),
        ),
        migrations.AlterField(
            model_name='rezeptzutat',
            name='rezept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezepte.Rezept'),
        ),
        migrations.AlterField(
            model_name='rezeptzutat',
            name='zutat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezepte.Zutat'),
        ),
    ]
