# Generated by Django 2.0.2 on 2019-03-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0002_auto_20180204_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezept',
            name='kommentar',
        ),
        migrations.AddField(
            model_name='menue',
            name='geschlossen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='slug',
            field=models.CharField(blank=True, help_text='wird i.d.R. aus titel berechnet', max_length=30),
        ),
        migrations.AlterField(
            model_name='rezeptzutat',
            name='menge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rezeptzutat',
            name='menge_qualitativ',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='zutat',
            name='einheit',
            field=models.CharField(default='', help_text='Packungseinheit für den Einkauf meist 1 kg, 1 l,\n             aber auch 2,5 kg-Sack.\n             Fällt weg bei Dingen wie Eiern, die eine natürliche Einheit\n             haben; dann "Stück"', max_length=10),
        ),
        migrations.AlterField(
            model_name='zutat',
            name='kategorie',
            field=models.CharField(choices=[('Milch', 'Milchprodukt'), ('Gemüse', 'Gemüse'), ('Obst', 'Obst'), ('Getr.', 'Getreide'), ('Grund.', 'Grundnahrungsmittel'), ('Fisch', 'Fisch'), ('Gewürz', 'Gewürz'), ('Sonst.', 'Sonstiges')], max_length=6, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='zutat',
            name='menge_pro_einheit',
            field=models.IntegerField(help_text='Anzahl der masseinheiten (s.u.) pro Packungseinheit; bei 1 kg: 1000'),
        ),
        migrations.AlterField(
            model_name='zutat',
            name='preis_pro_einheit',
            field=models.IntegerField(help_text='der Preis einer Packungseinheit; in Cent'),
        ),
    ]
