# Generated by Django 2.1.7 on 2019-03-22 21:23

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('rezepte', '0003_auto_20190322_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Mandant',
                'verbose_name_plural': 'Mandanten',
            },
        ),
        migrations.CreateModel(
            name='Gang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Gang',
                'verbose_name_plural': 'Gänge',
            },
        ),
        migrations.RemoveField(
            model_name='rezept',
            name='version',
        ),
        migrations.RemoveField(
            model_name='rezept',
            name='kategorie',
        ),
        migrations.AddField(
            model_name='rezept',
            name='kategorie',
            field=taggit.managers.TaggableManager(help_text='Art des Essens', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='slug',
            field=models.SlugField(blank=True, help_text='wird i.d.R. aus titel berechnet', max_length=30),
        ),
        migrations.RemoveField(
            model_name='zutat',
            name='kategorie',
        ),
        migrations.AddField(
            model_name='zutat',
            name='kategorie',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='client',
            name='gaenge',
            field=models.ManyToManyField(to='rezepte.Gang'),
        ),
        migrations.AddField(
            model_name='rezept',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rezepte.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zutat',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rezepte.Client'),
            preserve_default=False,
        ),
    ]
