# Generated by Django 2.1.7 on 2019-03-24 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0004_auto_20190322_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezept',
            name='zutaten',
        ),
        migrations.AddField(
            model_name='menue',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menues', to='rezepte.Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rezept',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezepte', to='rezepte.Client'),
        ),
        migrations.AlterField(
            model_name='rezeptzutat',
            name='rezept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zutaten', to='rezepte.Rezept'),
        ),
        migrations.AlterField(
            model_name='rezeptzutat',
            name='zutat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezepte', to='rezepte.Zutat'),
        ),
        migrations.AlterField(
            model_name='zutat',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zutaten', to='rezepte.Client'),
        ),
        migrations.AlterField(
            model_name='zutat',
            name='menge_pro_einheit',
            field=models.IntegerField(default=0, help_text='Anzahl der masseinheiten (s.u.) pro Packungseinheit; bei 1 kg: 1000'),
        ),
        migrations.AlterField(
            model_name='zutat',
            name='preis_pro_einheit',
            field=models.IntegerField(default=0, help_text='der Preis einer Packungseinheit; in Cent'),
        ),
    ]
