# Generated by Django 2.1.7 on 2019-03-25 04:24

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('rezepte', '0006_auto_20190324_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='RezeptKategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZutatKategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='rezeptzutat',
            options={'ordering': ('nummer',), 'verbose_name': 'Rezeptzutat', 'verbose_name_plural': 'Rezeptzutaten'},
        ),
        migrations.AlterField(
            model_name='rezept',
            name='kategorie',
            field=taggit.managers.TaggableManager(help_text='Art des Essens', through='rezepte.RezeptKategorie', to='taggit.Tag', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='zutat',
            name='kategorie',
            field=taggit.managers.TaggableManager(help_text='Art der Zutat', through='rezepte.ZutatKategorie', to='taggit.Tag', verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='zutatkategorie',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezepte.Zutat'),
        ),
        migrations.AddField(
            model_name='zutatkategorie',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezepte_zutatkategorie_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='rezeptkategorie',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezepte.Rezept'),
        ),
        migrations.AddField(
            model_name='rezeptkategorie',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezepte_rezeptkategorie_items', to='taggit.Tag'),
        ),
    ]
