# Generated by Django 2.1.7 on 2019-03-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0007_auto_20190325_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezept',
            name='untertitel',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zutat',
            name='menge_pro_einheit',
            field=models.IntegerField(default=0, help_text='Anzahl der Masseinheiten (s.u.) pro Packungseinheit; bei 1 kg: 1000'),
        ),
    ]
