# Generated by Django 2.1.7 on 2019-03-27 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0009_auto_20190326_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menue',
            name='hauptgang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hauptgang', to='rezepte.Rezept'),
        ),
        migrations.AlterField(
            model_name='menue',
            name='koch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='menue',
            name='nachtisch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nachtisch', to='rezepte.Rezept'),
        ),
        migrations.AlterField(
            model_name='menue',
            name='vorspeise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vorspeise', to='rezepte.Rezept'),
        ),
    ]
