# Generated by Django 2.1.7 on 2019-03-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0010_auto_20190327_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='untertitel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
