# Generated by Django 2.1.7 on 2019-03-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0011_auto_20190328_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='GangPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('gang', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Gangplan',
                'verbose_name_plural': 'Gangpläne',
            },
        ),
        migrations.RemoveField(
            model_name='menue',
            name='client',
        ),
        migrations.RemoveField(
            model_name='menue',
            name='hauptgang',
        ),
        migrations.RemoveField(
            model_name='menue',
            name='nachtisch',
        ),
        migrations.RemoveField(
            model_name='menue',
            name='vorspeise',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gaenge',
        ),
        migrations.AddField(
            model_name='client',
            name='gaenge',
            field=models.CharField(default='Vorspeise Hauptgang Nachtisch', help_text='z.B. "Vorspeise Hauptgang Nachtisch"', max_length=50),
        ),
        migrations.DeleteModel(
            name='Gang',
        ),
        migrations.DeleteModel(
            name='Menue',
        ),
        migrations.AddField(
            model_name='gangplan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menues', to='rezepte.Client'),
        ),
        migrations.AddField(
            model_name='gangplan',
            name='rezept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezepte.Rezept'),
        ),
    ]
