# Generated by Django 2.2.2 on 2019-06-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0014_auto_20190501_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='_preis',
            field=models.IntegerField(default=-1, help_text='kann leer sein, wird dann automatisch berechnet'),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='titel',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='zutat',
            name='menge_pro_einheit',
            field=models.IntegerField(default=0, help_text='Anzahl der Maßeinheiten pro Packungseinheit; bei 1 kg: 1000'),
        ),
        migrations.AlterField(
            model_name='zutat',
            name='preis_pro_einheit',
            field=models.IntegerField(default=-1, help_text='der Preis einer Packungseinheit; in Cent'),
        ),
    ]
