# Generated by Django 2.2.2 on 2019-06-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0015_auto_20190616_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezept',
            name='gang',
            field=models.CharField(default='Unsortiert', max_length=10),
            preserve_default=False,
        ),
    ]
