# Generated by Django 2.2.2 on 2019-08-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0016_rezept_gang'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='kategorien',
            field=models.CharField(default='', help_text='z.B. "Reis Teigwaren Getreide Kartoffeln Gemüse Suppe Fischgericht Lieblingsgericht"', max_length=100),
        ),
        migrations.AddField(
            model_name='rezept',
            name='kategorien',
            field=models.CharField(default='', help_text='Die Kategorie, zu der das Rezept gehört, ggf. eine Leerzeichen-getrennte Liste mehrerer Kategorien', max_length=60),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='gang',
            field=models.CharField(help_text='Der Gang, für den das Rezept geeignet ist, ggf. eine Leerzeichen-getrennte Liste mehrerer Gänge', max_length=40),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='slug',
            field=models.SlugField(blank=True, help_text='wird i.d.R. aus titel berechnet', max_length=60),
        ),
    ]
