# Generated by Django 2.2.4 on 2019-09-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0019_auto_20190912_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zutat',
            name='einheit',
            field=models.CharField(blank=True, default='', help_text='Packungseinheit für den Einkauf meist 1 kg, 1 l,\n             aber auch 2,5 kg-Sack.\n             Fällt weg bei Dingen wie Eiern, die eine natürliche Einheit\n             haben; dann "Stück"', max_length=30),
        ),
    ]
