# Generated by Django 2.2.4 on 2019-09-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0021_auto_20190912_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='slug',
            field=models.SlugField(blank=True, help_text='wird i.d.R. aus titel berechnet', max_length=100),
        ),
    ]
