# Generated by Django 3.0.2 on 2020-01-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0024_auto_20190912_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zutat',
            name='kategorie',
            field=models.CharField(choices=[('Milch', 'Milchprodukt'), ('Gemüse', 'Gemüse'), ('Obst', 'Obst'), ('Getr.', 'Getreide'), ('Grund.', 'Grundnahrungsmittel'), ('Fisch', 'Fisch'), ('Gewürz', 'Gewürz'), ('Sonst.', 'Sonstiges')], max_length=30),
        ),
    ]
