# Generated by Django 3.0.6 on 2020-05-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0025_auto_20200118_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Auf der Hauptseite verbergen', verbose_name='verborgen'),
        ),
    ]
