# Generated by Django 3.0.6 on 2020-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0026_client_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezept',
            name='_preis_dec',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kann leer sein, wird dann automatisch berechnet', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rezeptzutat',
            name='menge_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zutat',
            name='preis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='der Preis einer Packungseinheit; in Euro', max_digits=5, null=True),
        ),
    ]
