# Generated by Django 3.0.6 on 2020-05-31 17:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0026_client_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='zutat',
            name='preis',
            field=models.DecimalField(decimal_places=2, default=Decimal('-1'), help_text='der Preis einer Packungseinheit; in Euro', max_digits=5),
        ),
    ]
