# Generated by Django 3.0.6 on 2020-05-31 17:22

from django.db import migrations


def calc_preis(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Zutat = apps.get_model('rezepte', 'Zutat')
    for z in Zutat.objects.all():
        if z.preis_pro_einheit != -1:
            z.preis = z.preis_pro_einheit / 100.0
        z.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0027_zutat_preis'),
    ]

    operations = [
        migrations.RunPython(calc_preis),
    ]
