# Generated by Django 3.0.6 on 2020-06-26 09:12
from decimal import Decimal
from django.db import migrations


def calc_zutat_preis(apps, schema_editor):
    Zutat = apps.get_model('rezepte', 'Zutat')
    for z in Zutat.objects.all():
        if z.preis_pro_einheit != -1:
            z.preis = z.preis_pro_einheit / Decimal('100')
        z.save()


def calc_rezeptzutat_menge(apps, schema_editor):
    RezeptZutat = apps.get_model('rezepte', 'RezeptZutat')
    for rz in RezeptZutat.objects.all():
        rz.menge_int = int(rz.menge)
        rz.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0027_auto_20200626_1112'),
    ]

    operations = [
        migrations.RunPython(calc_zutat_preis),
        migrations.RunPython(calc_rezeptzutat_menge),
    ]
