# Generated by Django 3.0.6 on 2020-06-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0028_auto_20200626_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezept',
            name='_preis',
        ),
        migrations.RemoveField(
            model_name='rezeptzutat',
            name='menge',
        ),
        migrations.RemoveField(
            model_name='zutat',
            name='preis_pro_einheit',
        ),
    ]
