# Generated by Django 3.0.6 on 2020-06-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0028_auto_20200531_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezeptzutat',
            name='menge_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
