# Generated by Django 3.0.6 on 2020-06-07 05:09

from django.db import migrations


def calc_menge(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    RezeptZutat = apps.get_model('rezepte', 'RezeptZutat')
    for rz in RezeptZutat.objects.all():
        if rz.menge is not None:
            rz.menge_int = int(rz.menge)
        rz.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0029_rezeptzutat_menge_int'),
    ]

    operations = [
        migrations.RunPython(calc_menge),
    ]
