# Generated by Django 3.0.6 on 2020-06-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0029_auto_20200626_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezept',
            old_name='_preis_dec',
            new_name='_preis',
        ),
        migrations.RenameField(
            model_name='rezeptzutat',
            old_name='menge_int',
            new_name='menge',
        ),
    ]
