# Generated by Django 3.0.6 on 2020-07-27 06:26

from django.db import migrations


def create_providers(apps, schema_editor):
    Client = apps.get_model('rezepte', 'Client')
    Provider = apps.get_model('rezepte', 'Provider')
    for c in Client.objects.all():
        Provider.objects.create(
            name=c.name, slug=c.slug, client=c, gaenge=c.gaenge,
            kategorien=c.kategorien, hidden=c.hidden)


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0031_auto_20200727_0824'),
    ]

    operations = [
        migrations.RunPython(create_providers),
        migrations.RemoveField(
            model_name='client',
            name='gaenge',
        ),
        migrations.RemoveField(
            model_name='client',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='client',
            name='kategorien',
        ),
    ]
