# Generated by Django 3.0.6 on 2020-06-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0031_auto_20200611_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='_preis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kann leer sein, wird dann automatisch berechnet', max_digits=5, null=True),
        ),
    ]
