# Generated by Django 3.0.6 on 2020-07-27 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0032_auto_20200727_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rezepte', to='rezepte.Client'),
        ),
    ]
