# Generated by Django 3.0.6 on 2020-07-27 18:18

from django.db import migrations


def modify_rezepte(apps, schema_editor):
    Provider = apps.get_model('rezepte', 'Provider')
    for p in Provider.objects.all().select_related('client'):
        p.client.rezepte.all().update(provider=p)


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0033_auto_20200727_0839'),
    ]

    operations = [
        migrations.RunPython(modify_rezepte),
    ]
