# Generated by Django 3.0.6 on 2020-06-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0033_auto_20200611_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zutat',
            name='preis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='der Preis einer Packungseinheit; in Euro', max_digits=5, null=True),
        ),
    ]
