# Generated by Django 3.0.6 on 2020-07-29 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0034_auto_20200727_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mult_providers',
            field=models.BooleanField(default=False, verbose_name='Mehrere Einrichtungen'),
        ),
        migrations.AddField(
            model_name='provider',
            name='_domain',
            field=models.CharField(default='', max_length=32, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='rezepte.Client'),
        ),
    ]
