# Generated by Django 3.0.6 on 2020-08-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0035_auto_20200729_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezept',
            name='aktiv',
            field=models.BooleanField(default=True, help_text='Für die Planung verwenden', verbose_name='aktiv'),
        ),
    ]
