# Generated by Django 3.0.6 on 2020-08-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0036_rezept_aktiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezept',
            name='allergene',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='zutat',
            name='allergene',
            field=models.CharField(default='', max_length=20),
        ),
    ]
