# -*- coding: utf-8 -*-
from django.core.management.base import BaseCommand, CommandError

from rezepte.models import Rezept

data  = [{'slug': 'humus_mit_brot',
          'titel': 'Humus mit Brot',
          'untertitel': 'ganzes Jahr',
          'anmerkungen': None} ,
         {'slug': 'spinat_lasagne_luca',
          'titel': 'Spinat-Lasagne Luca',
          'untertitel': 'Ein Rezept von Tanja für das ganze Jahr',
          'anmerkungen': None} ,
         {'slug': 'moehrenrisotto',
          'titel': 'Möhrenrisotto',
          'untertitel': 'Ein Rezept von Susanne Louven-Kemna',
          'anmerkungen': None} ,
         {'slug': 'kuerbislasagne',
          'titel': 'Kürbislasagne',
          'untertitel': 'Bewährtes Kita-Rezept für ein Gericht von September bis April',
          'anmerkungen': None} ,
         {'slug': 'griechischer_bauernsalat',
          'titel': 'Griechischer Bauernsalat',
          'untertitel': 'Ein Rezept von Susanne Louven-Kemna',
          'anmerkungen': None} ,
         {'slug': 'gewuerzmoehren_mit_hirse',
          'titel': 'Gewürzmöhren mit Hirse',
          'untertitel': 'Falls möglich Möhren mit Grün liefern lassen',
          'anmerkungen': None} ,
         {'slug': 'buchweizenauflauf',
          'titel': 'Buchweizenauflauf',
          'untertitel': 'Rezept für das ganze Jahr',
          'anmerkungen': None} ,
         {'slug': 'geduenstete_moehren_mit_mais',
          'titel': 'gedünstete Möhren mit Mais',
          'untertitel': 'Wird nicht gerne gegessen!',
          'anmerkungen': None} ,
         {'slug': 'broccolicremesuppe_mit_croutons',
          'titel': 'Broccolicremesuppe mit Croutons',
          'untertitel': 'Ein Rezept von Franzi Matoni',
          'anmerkungen': None} ,
         {'slug': 'blattsalat',
          'titel': 'Blattsalat',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'gnocchi_gemuese_pfanne',
          'titel': 'Gnocchi-Gemüse-Pfanne',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'apfelrotkohl_mit_kartoffelpueree',
          'titel': 'Apfelrotkohl mit Kartoffelpüree',
          'untertitel': 'Wintergericht',
          'anmerkungen': None} ,
         {'slug': 'rigatoni_verdi',
          'titel': 'Rigatoni verdi',
          'untertitel': 'Rezept von Andrea Gutzmann',
          'anmerkungen': None} ,
         {'slug': 'seemannskonfetti',
          'titel': 'Seemannskonfetti',
          'untertitel': 'in Anlehnung an "Kochen für Kindergruppen" Katrin Raschke',
          'anmerkungen': None} ,
         {'slug': 'gelbe_linsensuppe_mit_orangensaft',
          'titel': 'gelbe Linsensuppe mit Orangensaft',
          'untertitel': 'ein Rezept von Sabine Hattenkerl für ein Gericht im ganzen Jahr',
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'obstsalat_i',
          'titel': 'Obstsalat I.',
          'untertitel': None,
          'anmerkungen': 'Bitte eine\xa0Rückstellprobe anfertigen!'} ,
         {'slug': 'moehren_kokosmilchsuppe',
          'titel': 'Möhren-Kokosmilchsuppe ',
          'untertitel': None,
          'anmerkungen': 'Bitta eine Rückstellprobe anfertigen.'} ,
         {'slug': 'eintopf_mit_chinakohl',
          'titel': 'Eintopf mit Chinakohl',
          'untertitel': 'Wintergericht',
          'anmerkungen': None} ,
         {'slug': 'verstecktes_gemuese',
          'titel': 'Verstecktes Gemüse',
          'untertitel': 'Für den Winter, da mit TK-Gemüse zuzubereiten',
          'anmerkungen': None} ,
         {'slug': 'griessflammerie_mit_obst',
          'titel': 'Griessflammerie mit Obst',
          'untertitel': 'Rezept von Susanne luven-Kemna für ein Gericht im ganzen Jahr (u.U. das Obst variieren)',
          'anmerkungen': None} ,
         {'slug': 'spinat_lasagne',
          'titel': 'Spinat-Lasagne',
          'untertitel': 'Rezept von Tine German-Nagels',
          'anmerkungen': None} ,
         {'slug': 'vanillepudding_mit_birnen',
          'titel': 'Vanillepudding mit Birnen',
          'untertitel': 'Obst nach Saison ',
          'anmerkungen': None} ,
         {'slug': 'bunter_gemuesekuchen',
          'titel': 'Bunter Gemüsekuchen',
          'untertitel': 'Rezept von Silke Bacht',
          'anmerkungen': None} ,
         {'slug': 'tomatensuppe_mit_mozarella',
          'titel': 'Tomatensuppe mit Mozarella',
          'untertitel': 'Rezept von Franzi für ein Gericht im Sommer',
          'anmerkungen': None} ,
         {'slug': 'pellkartoffeln_mit_kraeuterquark',
          'titel': 'Pellkartoffeln mit Kräuterquark',
          'untertitel': 'Ein Gericht für den Frühsommer',
          'anmerkungen': None} ,
         {'slug': 'gegrillte_maiskolben',
          'titel': 'gegrillte Maiskolben',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'kartoffel_frittata_mit_blattsalat',
          'titel': 'Kartoffel-Frittata mit Blattsalat',
          'untertitel': 'Ein Rezept für das ganze Jahr / Zur Tomatenzeit auch frische Tomaten möglich!',
          'anmerkungen': None} ,
         {'slug': 'fruchtiger_milchreis_mit_kruste',
          'titel': 'fruchtiger Milchreis mit Kruste',
          'untertitel': 'Rezept von Janine',
          'anmerkungen': None} ,
         {'slug': 'polenta_lauch_auflauf',
          'titel': 'Polenta-Lauch-Auflauf',
          'untertitel': 'Ein Rezept von Torsten Hattenkerl für ein Gericht im ganzen Jahr',
          'anmerkungen': None} ,
         {'slug': 'thunfischbratlinge_mit_moehrensalat_und_dipp',
          'titel': 'Thunfischbratlinge mit Möhrensalat und Dipp',
          'untertitel': None,
          'anmerkungen': 'Bitte für Marie-France Dinkel-Burger mit Thunfisch und geraspelten Möhren machen'} ,
         {'slug': 'weisskohlsalat_mit_ananas',
          'titel': 'Weißkohlsalat mit Ananas',
          'untertitel': 'Die Kinder essen den Salat nicht gerne, zum großen Teil gar nicht!',
          'anmerkungen': None} ,
         {'slug': 'risotto_mit_tofu',
          'titel': 'Risotto mit Tofu',
          'untertitel': 'Ein Rezept von Uschi Lepski\nRISOTTOREIS WURDE DURCH EINFACHEN REIS ERSETZT, DA NACH MEINUNG DES \n"KOCHS" DER RISOTTOREIS ZU MÄCHTIG WAR. BITTE SELBST ENTSCHEIDEN!',
          'anmerkungen': None} ,
         {'slug': 'vollkornbaguette__vollkorntoast_vollkornbroetchen',
          'titel': 'Vollkornbaguette/ Vollkorntoast/Vollkornbrötchen',
          'untertitel': None,
          'anmerkungen': 'Das Gericht enthält folgende Allergene: glutenhaltiges Getreide'} ,
         {'slug': 'gemuesepaella',
          'titel': 'Gemüsepaella',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'schaelerbsensuppe',
          'titel': 'Schälerbsensuppe',
          'untertitel': 'Rezept von Silke Bacht',
          'anmerkungen': None} ,
         {'slug': 'reis_mit_pilzsahnesosse',
          'titel': 'Reis mit Pilzsahnesoße',
          'untertitel': 'Gericht für den Herbst',
          'anmerkungen': None} ,
         {'slug': 'cremige_rote_beete_suppe',
          'titel': 'Cremige Rote-Beete-Suppe',
          'untertitel': 'Ein Rezept für den Winter',
          'anmerkungen': None} ,
         {'slug': 'spargelcremesuppe_mit_kartoffelstueckchen',
          'titel': 'Spargelcremesuppe mit Kartoffelstückchen',
          'untertitel': 'Mai/Juni Gericht\n',
          'anmerkungen': None} ,
         {'slug': 'salat_mit_sonnenblumenkernen',
          'titel': 'Salat mit Sonnenblumenkernen',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'pizzaschnecken',
          'titel': 'Pizzaschnecken',
          'untertitel': 'Ein Rezept von Gisela Vos-Ammon für das ganze Jahr!',
          'anmerkungen': None} ,
         {'slug': 'stielmus_gruenkern_auflauf',
          'titel': 'Stielmus-Grünkern-Auflauf',
          'untertitel': 'Ein Rezept von Andrea B. zur Stielmus-Zeit',
          'anmerkungen': None} ,
         {'slug': 'hirseschnitzel_mit_tomatensosse___dipp',
          'titel': 'Hirseschnitzel mit Tomatensoße / Dipp\t\t\t\t ',
          'untertitel': 'Rezept von Andrea Barck',
          'anmerkungen': None} ,
         {'slug': 'erdbeeren__auf_griespudding',
          'titel': 'Erdbeeren  auf Griespudding',
          'untertitel': 'Zur Erdbeer-Saison',
          'anmerkungen': None} ,
         {'slug': 'zucchinicremesuppe',
          'titel': 'Zucchinicremesuppe',
          'untertitel': 'Rezept für den Sommer/Herbst',
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'cous_cous_salat',
          'titel': 'Cous-Cous-Salat',
          'untertitel': 'Rezept von Ann Gaelle',
          'anmerkungen': None} ,
         {'slug': 'weintrauben',
          'titel': 'Weintrauben',
          'untertitel': 'Gericht für den Spätsommer/Herbst'} ,
         {'slug': 'tomaten_gurken_salat_mit_feta',
          'titel': 'Tomaten-Gurken-Salat mit Feta',
          'untertitel': 'Rezept von Valentina',
          'anmerkungen': None} ,
         {'slug': 'zwetschgen_crumble',
          'titel': 'Zwetschgen-Crumble',
          'untertitel': '\n',
          'anmerkungen': None} ,
         {'slug': 'lauchkuchen_mit_raeuchertofu',
          'titel': 'Lauchkuchen mit Räuchertofu',
          'untertitel': 'Rezept von Carole Müller',
          'anmerkungen': None} ,
         {'slug': 'fraenkischer_kartoffelsalat',
          'titel': 'Fränkischer Kartoffelsalat',
          'untertitel': 'Ein Gericht für den Sommer',
          'anmerkungen': None} ,
         {'slug': 'mangold_kohlrabi_lasagne',
          'titel': 'Mangold-Kohlrabi-Lasagne',
          'untertitel': 'Wintergericht',
          'anmerkungen': None} ,
         {'slug': 'vegetable_fried_rice',
          'titel': 'Vegetable fried rice',
          'untertitel': 'Ein Rezept von Susanne Louven-Kemna für ein Gericht im ganzen Jahr',
          'anmerkungen': None} ,
         {'slug': 'ananas',
          'titel': 'Ananas',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'himbeertraum_im_quarkbett',
          'titel': 'Himbeertraum im Quarkbett',
          'untertitel': 'Rezept von Andrea Barck',
          'anmerkungen': None} ,
         {'slug': 'moehren_orangen_salat',
          'titel': 'Möhren-Orangen-Salat',
          'untertitel': 'Rezept von Ann Gaelle',
          'anmerkungen': None} ,
         {'slug': 'krautfleckerln',
          'titel': 'Krautfleckerln',
          'untertitel': 'Rezept von Andrea Barck'} ,
         {'slug': 'gemischter_salat__mais_und_gurke',
          'titel': 'Gemischter Salat (Mais und Gurke)',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'blattsalat_mit_roter_beete',
          'titel': 'Blattsalat mit roter Beete',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'polentastreifen_auf_fruehlingssalat',
          'titel': 'Polentastreifen auf Frühlingssalat',
          'untertitel': 'Das Gericht bitte ohne Vorspeise und mit einer gehaltvollen Nachspeise kochen.',
          'anmerkungen': None} ,
         {'slug': 'erdbeerquark_mit_baiserstueckchen',
          'titel': 'Erdbeerquark mit Baiserstückchen',
          'untertitel': 'Rezept zur Erdbeerzeit',
          'anmerkungen': None} ,
         {'slug': 'gemueserisotto_mit_sojahackbaellchen',
          'titel': 'Gemüserisotto mit Sojahackbällchen',
          'untertitel': 'Ein Rezept von Ann-Gäelle'} ,
         {'slug': 'bella_italia',
          'titel': 'Bella italia',
          'untertitel': 'Rezept von Andrea Barck für ein Gericht im Sommer/Herbst',
          'anmerkungen': None} ,
         {'slug': 'buchstabensuppe',
          'titel': 'Buchstabensuppe',
          'untertitel': 'Ein Rezept von Andrea Gutzmann',
          'anmerkungen': None} ,
         {'slug': 'polentatorte_mit_mangold',
          'titel': 'Polentatorte mit Mangold',
          'untertitel': 'Ein Rezept von Andrea B. für die Mangoldzeit',
          'anmerkungen': None} ,
         {'slug': 'bratapfel__knecht_ruprecht',
          'titel': 'Bratapfel "Knecht-Ruprecht"',
          'untertitel': 'Rezept für die Winterzeit von Ellen',
          'anmerkungen': None} ,
         {'slug': 'fruchteis',
          'titel': 'Fruchteis',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'lasagne_al_forno',
          'titel': 'Lasagne al forno',
          'untertitel': 'Ein Gericht für das ganze Jahr',
          'anmerkungen': None} ,
         {'slug': 'apfel_moehren_salat',
          'titel': 'Apfel-Möhren-Salat',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'gemuese_gratin',
          'titel': 'Gemüse Gratin',
          'untertitel': 'Rezept von Ann Gaelle',
          'anmerkungen': None} ,
         {'slug': 'vanillepudding_mit_frischen_himbeeren_und_aprikosen',
          'titel': 'Vanillepudding mit frischen Himbeeren und Aprikosen',
          'untertitel': 'Nur in der Saison! Ansonsten bitte anderes frisches Obst der Saison verwenden.',
          'anmerkungen': None} ,
         {'slug': 'mairuebchensuppe',
          'titel': 'Mairübchensuppe ',
          'untertitel': 'Zur Mairübchenzeit',
          'anmerkungen': None} ,
         {'slug': '3k_ragout',
          'titel': '3K Ragout ',
          'untertitel': 'Herbst/Winter-Rezept',
          'anmerkungen': None} ,
         {'slug': 'geduensteter_moehrensalat',
          'titel': 'gedünsteter Möhrensalat',
          'untertitel': 'Rezept von Andrea Barck',
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'pfannkuchen_mit_apfelmus',
          'titel': 'Pfannkuchen mit Apfelmus',
          'untertitel': 'Rezept von Franzi',
          'anmerkungen': None} ,
         {'slug': 'salat_mit_mais',
          'titel': 'Salat mit Mais',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'spinat_reis_auflauf',
          'titel': 'Spinat-Reis-Auflauf',
          'untertitel': 'Ein Rezept aus dem Kita-Kochordner für ein Gericht im ganzen Jahr',
          'anmerkungen': None} ,
         {'slug': 'zucchinipuffer_mit_kraeuterquark',
          'titel': 'Zucchinipuffer mit Kräuterquark',
          'untertitel': 'Rezept von Valentina für ein Gericht im Sommer',
          'anmerkungen': None} ,
         {'slug': 'minipfannkuchen_mit_sommerlichen_leckereien',
          'titel': 'Minipfannkuchen mit sommerlichen Leckereien',
          'untertitel': 'Rezept von Sabine Hattenkerl',
          'anmerkungen': None} ,
         {'slug': 'minestrone_mit_hirse',
          'titel': 'Minestrone mit Hirse',
          'untertitel': 'Rezept von Uschi Lepski',
          'anmerkungen': None} ,
         {'slug': 'milchreis_mit_frischen_erdbeeren',
          'titel': 'Milchreis mit frischen Erdbeeren',
          'untertitel': 'Zur Erdbeersaison',
          'anmerkungen': None} ,
         {'slug': 'tortellinisalat__lauwarm',
          'titel': 'Tortellinisalat, lauwarm',
          'untertitel': 'Rezept von Andrea Barck für ein Gericht im Sommer oder Herbst',
          'anmerkungen': None} ,
         {'slug': 'spaghetti_mit_sahnesauce__broccoli__pilzen_und_lauch',
          'titel': 'Spaghetti mit Sahnesauce, Broccoli, Pilzen und Lauch',
          'untertitel': 'Ein Rezept von Familie Gutzmann',
          'anmerkungen': None} ,
         {'slug': 'gemischter_salat',
          'titel': 'gemischter Salat',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'spanischer_mandelkuchen',
          'titel': 'Spanischer Mandelkuchen',
          'untertitel': 'Ein Rezept von Steffi Vogler',
          'anmerkungen': None} ,
         {'slug': 'schupfnudeln_in_broesel_mit_vanillesauce',
          'titel': 'Schupfnudeln in Brösel mit Vanillesauce',
          'untertitel': 'Ein Gericht von Andrea Barck für das ganze Jahr',
          'anmerkungen': None} ,
         {'slug': 'nudel_spinat_auflauf',
          'titel': 'Nudel-Spinat-Auflauf',
          'untertitel': 'Rezept für ein Gericht im ganzen Jahr',
          'anmerkungen': None} ,
         {'slug': 'reis_mit_bunter_gemuesesauce',
          'titel': 'Reis mit bunter Gemüsesauce',
          'untertitel': 'Ein Rezept von Silke Bacht',
          'anmerkungen': None} ,
         {'slug': 'scheiterhaufen',
          'titel': 'Scheiterhaufen',
          'untertitel': 'Rezept von Andrea Barck, am Vortag müssen halbbackene Brötchen gebacken werden.',
          'anmerkungen': None} ,
         {'slug': 'snowdonia_trifle',
          'titel': 'Snowdonia Trifle',
          'untertitel': 'Ein Rezept von Sabine Hattenkerl',
          'anmerkungen': None} ,
         {'slug': 'gemuesesuppe_mit__buschbohnen',
          'titel': 'Gemüsesuppe mit  Buschbohnen',
          'untertitel': 'Rezept für Sommer/Herbst',
          'anmerkungen': None} ,
         {'slug': 'kaiserschmarrn',
          'titel': 'Kaiserschmarrn',
          'untertitel': 'Vorsicht, kann leicht anbrennen\nRezept von Gisela Vos-Ammon',
          'anmerkungen': None} ,
         {'slug': 'gemuesepolenta_mit_tomatenrahm',
          'titel': 'Gemüsepolenta mit Tomatenrahm',
          'untertitel': 'Rezept von Sabine Hattenkerl für ein Gericht im ganzen Jahr',
          'anmerkungen': None} ,
         {'slug': 'ueberbackene_bananen_in_orangensauce',
          'titel': 'Überbackene Bananen in Orangensauce',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'tabuleh',
          'titel': 'Tabuleh',
          'untertitel': 'Rezept von Sabine Hattenkerl für ein Gericht im Sommer',
          'anmerkungen': None} ,
         {'slug': 'gegrillte_maiskolben1',
          'titel': 'Gegrillte Maiskolben',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'eisbergsalat_mit_apfelstueckchen',
          'titel': 'Eisbergsalat mit Apfelstückchen',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'apfelmus',
          'titel': 'Apfelmus ',
          'untertitel': None,
          'anmerkungen': 'Bitte vom Selbstgekochtem Apfelmus eine Rückstellprobe anfertigen.'} ,
         {'slug': 'kartoffel_weisskohlroesti_mit_dipp',
          'titel': 'Kartoffel-Weißkohlrösti mit Dipp',
          'untertitel': 'Wintergericht',
          'anmerkungen': None} ,
         {'slug': 'nudeln_mit_fenchelsauce',
          'titel': 'Nudeln mit Fenchelsauce',
          'untertitel': 'Wintergericht (Fenchel)',
          'anmerkungen': None} ,
         {'slug': 'apfel_crumble',
          'titel': 'Apfel-Crumble',
          'untertitel': 'Ein Rezept von Katrin K.',
          'anmerkungen': None} ,
         {'slug': 'marillenknoedel_in_butterbroesel',
          'titel': 'Marillenknödel in Butterbrösel',
          'untertitel': 'Ein Gericht von Andrea B. für das ganze Jahr',
          'anmerkungen': None} ,
         {'slug': 'salat_mit_gurke_und_mais',
          'titel': 'Salat mit Gurke und Mais',
          'untertitel': None,
          'anmerkungen': 'Biite eine Rückstellprobe anfertigen.'} ,
         {'slug': 'kuerbisgnocchi_mit_tomaten_und_parmesan',
          'titel': 'Kürbisgnocchi mit Tomaten und Parmesan',
          'untertitel': 'Ein Rezept von Andrea Barck für ein Gericht von September bis April',
          'anmerkungen': None} ,
         {'slug': 'moehrencarpaccio',
          'titel': 'Möhrencarpaccio',
          'untertitel': 'Rezept für das ganze Jahr',
          'anmerkungen': None} ,
         {'slug': 'kraeutergnocchi_mit_pilzen',
          'titel': 'Kräutergnocchi mit Pilzen',
          'untertitel': 'Rezept von Andrea Barck',
          'anmerkungen': None} ,
         {'slug': 'flammenkuchen',
          'titel': 'Flammenkuchen',
          'untertitel': 'Elsässisches Rezept',
          'anmerkungen': None} ,
         {'slug': 'klare_suppe_mit_gemuese__reiseinlage',
          'titel': 'Klare Suppe mit Gemüse-/Reiseinlage',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,
         {'slug': 'ueberbackene_spinatpfannkuchen',
          'titel': 'Überbackene Spinatpfannkuchen ',
          'untertitel': 'Ein Rezept von Gisela Vos-Ammon für ein Gericht im ganzen Jahr',
          'anmerkungen': None} ,
         {'slug': 'latte_ros',
          'titel': 'Latte rosé',
          'untertitel': 'Zur Erdbeerzeit',
          'anmerkungen': None} ,
         {'slug': 'gemuesesuppe_mit_nudeln_und_tofu',
          'titel': 'Gemüsesuppe mit Nudeln und Tofu',
          'untertitel': 'Rezept von Valentina Piepers',
          'anmerkungen': None} ,
         {'slug': 'moehren_trauben_salat',
          'titel': 'Möhren-Trauben-Salat',
          'untertitel': None,
          'anmerkungen': 'Bitte eine Rückstellprobe anfertigen.'} ,]

class Command(BaseCommand):
    help = ('Trägt fehlende Daten der Kita Pusteblume nach')

    def handle(self, *args, **options):
        n = 0
        for r in data:
            try:
                titel = r['titel']
                rezept = Rezept.objects.get(titel=titel)
            except Rezept.DoesNotExist:
                self.stdout.write(f'NotFound - "{titel}" nicht gefunden.')
                continue
            except Rezept.MultipleObjectsReturned:
                self.stdout.write(f'Multiple - "{titel}" existiert mehrfach.')
                continue
            untertitel = r.get('untertitel', '')
            anmerkungen = r.get('anmerkungen', '')
            if rezept.untertitel:
                self.stdout.write(f'Rezept "{titel}" hat schon Untertitel "{rezept.untertitel}".')
                if rezept.untertitel == untertitel:
                    self.stdout.write(f'    Die Untertitel wären gleich.')
                else:
                    self.stdout.write(f'    Der neue Untertitel wäre {untertitel}.')
                if rezept.anmerkungen == anmerkungen:
                    self.stdout.write(f'    Die Anmerkungen wären gleich.')
                else:
                    self.stdout.write(f'    Anmerkungen alt: {rezept.anmerkungen}.')
                    self.stdout.write(f'    Anmerkungen neu: {anmerkungen}.')
                continue
            if rezept.anmerkungen:
                self.stdout.write(f'Rezept "{titel}" hat schon Anmerkungen "{rezept.anmerkungen}".')
                if rezept.anmerkungen == anmerkungen:
                    self.stdout.write(f'    Die Anmerkungen wären gleich.')
                else:
                    self.stdout.write(f'    Die neuen Anmerkungen wäre {anmerkungen}.')
                if rezept.untertitel == untertitel:
                    self.stdout.write(f'    Die Untertitel wären gleich.')
                else:
                    self.stdout.write(f'    Untertitel alt: {rezept.untertitel}.')
                    self.stdout.write(f'    Untertitel neu: {untertitel}.')
                continue
            if len(untertitel)>=100:
                self.stdout.write(f'Too long - Bei "{titel}" ist der Untertitel zu lang: "{untertitel}".')
                continue
            rezept.untertitel = untertitel
            rezept.anmerkungen = anmerkungen
            rezept.save()
            n += 1
        self.stdout.write(f'{n} Rezepte aktualisiert.')
